set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets opCode[2]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets opCode[1]]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets opCode[0]]

set_property IOSTANDARD LVCMOS33 [get_ports aluOp]
set_property IOSTANDARD LVCMOS33 [get_ports aluSrc]
set_property IOSTANDARD LVCMOS33 [get_ports memRead]
set_property IOSTANDARD LVCMOS33 [get_ports memToReg]
set_property IOSTANDARD LVCMOS33 [get_ports memWrite]
set_property IOSTANDARD LVCMOS33 [get_ports regWrite]
set_property IOSTANDARD LVCMOS33 [get_ports {opCode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {opCode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {opCode[0]}]

set_property PACKAGE_PIN L1 [get_ports aluOp]
set_property PACKAGE_PIN P1 [get_ports aluSrc]
set_property PACKAGE_PIN N3 [get_ports memRead]
set_property PACKAGE_PIN P3 [get_ports memToReg]
set_property PACKAGE_PIN U3 [get_ports memWrite]
set_property PACKAGE_PIN W3 [get_ports regWrite]
set_property PACKAGE_PIN W16 [get_ports {opCode[1]}]
set_property PACKAGE_PIN V16 [get_ports {opCode[0]}]

set_property PACKAGE_PIN V17 [get_ports {opCode[2]}]
